// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIPAD.Infrastructure.Data;

#nullable disable

namespace SIPAD.Infrastructure.Migrations
{
    [DbContext(typeof(SipadDbContext))]
    [Migration("20260307020310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIPAD.Domain.Entities.AbandonoCausanteZona", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_registro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegistro"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<int?>("CasosReportados")
                        .HasColumnType("integer")
                        .HasColumnName("casos_reportados");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdCausante")
                        .HasColumnType("integer")
                        .HasColumnName("id_causante");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    b.Property<decimal?>("PesoCausal")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_causal");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdCausante");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("abandono_causantes_zona", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.CausanteAbandono", b =>
                {
                    b.Property<int>("IdCausante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_causante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCausante"));

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreCausante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_causante");

                    b.HasKey("IdCausante");

                    b.ToTable("causantes_abandono", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.CentroEducativo", b =>
                {
                    b.Property<int>("IdCentro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_centro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCentro"));

                    b.Property<string>("CodigoCentro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_centro");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<int>("IdDistrito")
                        .HasColumnType("integer")
                        .HasColumnName("id_distrito");

                    b.Property<int?>("IdMunicipio")
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric")
                        .HasColumnName("longitud");

                    b.Property<int?>("MunicipioIdMunicipio")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("NombreCentro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_centro");

                    b.Property<string>("Sector")
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zona")
                        .HasColumnType("text")
                        .HasColumnName("zona");

                    b.HasKey("IdCentro");

                    b.HasIndex("CodigoCentro")
                        .IsUnique();

                    b.HasIndex("IdDistrito");

                    b.HasIndex("MunicipioIdMunicipio");

                    b.ToTable("centros_educativos", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.DemocratizacionEducativa", b =>
                {
                    b.Property<int>("IdDemocratizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_democratizacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDemocratizacion"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<decimal?>("BrechaUrbanoRural")
                        .HasColumnType("numeric")
                        .HasColumnName("brecha_urbano_rural");

                    b.Property<decimal?>("CentrosPorMilEstudiantes")
                        .HasColumnType("numeric")
                        .HasColumnName("centros_por_mil_estudiantes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DistanciaPromedioCentroKm")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia_promedio_centro_km");

                    b.Property<string>("FuenteDatos")
                        .HasColumnType("text")
                        .HasColumnName("fuente_datos");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    b.Property<decimal?>("IndiceInequidadEducativa")
                        .HasColumnType("numeric")
                        .HasColumnName("indice_inequidad_educativa");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("text")
                        .HasColumnName("nivel_educativo");

                    b.Property<decimal?>("TasaCoberturaNeta")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_cobertura_neta");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdDemocratizacion");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("democratizacion_educativa", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.DistritoEducativo", b =>
                {
                    b.Property<int>("IdDistrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_distrito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDistrito"));

                    b.Property<string>("CodigoDistrito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_distrito");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("IdMunicipio")
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    b.Property<int?>("IdProvincia")
                        .HasColumnType("integer")
                        .HasColumnName("id_provincia");

                    b.Property<int>("IdRegional")
                        .HasColumnType("integer")
                        .HasColumnName("id_regional");

                    b.Property<int?>("MunicipioIdMunicipio")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDistrito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_distrito");

                    b.Property<int?>("ProvinciaIdProvincia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdDistrito");

                    b.HasIndex("IdRegional");

                    b.HasIndex("MunicipioIdMunicipio");

                    b.HasIndex("ProvinciaIdProvincia");

                    b.ToTable("distritos_educativos", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.EstadisticaAbandono", b =>
                {
                    b.Property<int>("IdEstadistica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estadistica");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadistica"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdCentro")
                        .HasColumnType("integer")
                        .HasColumnName("id_centro");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("integer")
                        .HasColumnName("id_periodo");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("text")
                        .HasColumnName("nivel_educativo");

                    b.Property<decimal?>("TasaAbandonoInteranual")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_abandono_interanual");

                    b.Property<decimal?>("TasaDesercionHistorica")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_desercion_historica");

                    b.Property<int?>("TotalAbandonos")
                        .HasColumnType("integer")
                        .HasColumnName("total_abandonos");

                    b.Property<int?>("TotalMatriculados")
                        .HasColumnType("integer")
                        .HasColumnName("total_matriculados");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdEstadistica");

                    b.HasIndex("IdCentro");

                    b.HasIndex("IdPeriodo");

                    b.ToTable("estadisticas_abandono", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.FactorRiesgoSocial", b =>
                {
                    b.Property<int>("IdRiesgoSocial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_riesgo_social");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRiesgoSocial"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<int?>("CasosViolenciaIntrafamiliar")
                        .HasColumnType("integer")
                        .HasColumnName("casos_violencia_intrafamiliar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FuenteDatos")
                        .HasColumnType("text")
                        .HasColumnName("fuente_datos");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    b.Property<decimal?>("IndiceDelincuenciaJuvenil")
                        .HasColumnType("numeric")
                        .HasColumnName("indice_delincuencia_juvenil");

                    b.Property<decimal?>("IndiceDesintegracionFamiliar")
                        .HasColumnType("numeric")
                        .HasColumnName("indice_desintegracion_familiar");

                    b.Property<decimal?>("TasaConsumoSustancias")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_consumo_sustancias");

                    b.Property<decimal?>("TasaEmbarazoAdolescente")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_embarazo_adolescente");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdRiesgoSocial");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("factores_riesgo_social", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.IndicadorSocioeconomico", b =>
                {
                    b.Property<int>("IdIndicadorSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_indicador_socio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIndicadorSocio"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FuenteDatos")
                        .HasColumnType("text")
                        .HasColumnName("fuente_datos");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    b.Property<decimal?>("IndiceTrabajoInfantil")
                        .HasColumnType("numeric")
                        .HasColumnName("indice_trabajo_infantil");

                    b.Property<decimal?>("IngresoPromedioMensual")
                        .HasColumnType("numeric")
                        .HasColumnName("ingreso_promedio_mensual");

                    b.Property<decimal?>("NivelInformalidadLaboral")
                        .HasColumnType("numeric")
                        .HasColumnName("nivel_informalidad_laboral");

                    b.Property<decimal?>("TasaDesempleo")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_desempleo");

                    b.Property<decimal?>("TasaPobrezaExtrema")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_pobreza_extrema");

                    b.Property<decimal?>("TasaPobrezaMonetaria")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_pobreza_monetaria");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdIndicadorSocio");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("indicadores_socioeconomicos", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMunicipio"));

                    b.Property<decimal?>("AreaKm2")
                        .HasColumnType("numeric")
                        .HasColumnName("area_km2");

                    b.Property<string>("CodigoMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_municipio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("integer")
                        .HasColumnName("id_provincia");

                    b.Property<string>("NombreMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_municipio");

                    b.Property<int?>("PoblacionEstimada")
                        .HasColumnType("integer")
                        .HasColumnName("poblacion_estimada");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdMunicipio");

                    b.HasIndex("CodigoMunicipio")
                        .IsUnique();

                    b.HasIndex("IdProvincia");

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.PeriodoAcademico", b =>
                {
                    b.Property<int>("IdPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_periodo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPeriodo"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("AnioEscolar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("anio_escolar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Periodo")
                        .HasColumnType("text")
                        .HasColumnName("periodo");

                    b.HasKey("IdPeriodo");

                    b.ToTable("periodos_academicos", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_provincia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("CodigoProvincia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_provincia");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_provincia");

                    b.Property<string>("RegionGeografica")
                        .HasColumnType("text")
                        .HasColumnName("region_geografica");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("IdProvincia");

                    b.HasIndex("CodigoProvincia")
                        .IsUnique();

                    b.ToTable("provincias", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.RecursoEducativo", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_recurso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecurso"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisponibilidadMaterialesDidacticos")
                        .HasColumnType("text")
                        .HasColumnName("disponibilidad_materiales_didacticos");

                    b.Property<string>("EstadoInfraestructura")
                        .HasColumnType("text")
                        .HasColumnName("estado_infraestructura");

                    b.Property<int>("IdCentro")
                        .HasColumnType("integer")
                        .HasColumnName("id_centro");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("integer")
                        .HasColumnName("id_periodo");

                    b.Property<bool>("ProgramaAlimentacionEscolar")
                        .HasColumnType("boolean")
                        .HasColumnName("programa_alimentacion_escolar");

                    b.Property<bool>("ProgramaTransporteEscolar")
                        .HasColumnType("boolean")
                        .HasColumnName("programa_transporte_escolar");

                    b.Property<decimal?>("RatioEstudianteDocente")
                        .HasColumnType("numeric")
                        .HasColumnName("ratio_estudiante_docente");

                    b.Property<bool>("TieneBiblioteca")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_biblioteca");

                    b.Property<bool>("TieneLaboratorio")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_laboratorio");

                    b.Property<bool>("TieneTecnologiaEducativa")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_tecnologia_educativa");

                    b.Property<int?>("TotalDocentes")
                        .HasColumnType("integer")
                        .HasColumnName("total_docentes");

                    b.Property<int?>("TotalEstudiantes")
                        .HasColumnType("integer")
                        .HasColumnName("total_estudiantes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdRecurso");

                    b.HasIndex("IdCentro");

                    b.HasIndex("IdPeriodo");

                    b.ToTable("recursos_educativos", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.RegionalEducativa", b =>
                {
                    b.Property<int>("IdRegional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_regional");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegional"));

                    b.Property<string>("CodigoRegional")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_regional");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NombreRegional")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_regional");

                    b.Property<string>("SedeRegional")
                        .HasColumnType("text")
                        .HasColumnName("sede_regional");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdRegional");

                    b.ToTable("regionales_educativas", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.RendimientoAcademico", b =>
                {
                    b.Property<int>("IdRendimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rendimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRendimiento"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EstudiantesAprobados")
                        .HasColumnType("integer")
                        .HasColumnName("estudiantes_aprobados");

                    b.Property<int?>("EstudiantesReprobados")
                        .HasColumnType("integer")
                        .HasColumnName("estudiantes_reprobados");

                    b.Property<int?>("EstudiantesSobreedad")
                        .HasColumnType("integer")
                        .HasColumnName("estudiantes_sobreedad");

                    b.Property<int>("IdCentro")
                        .HasColumnType("integer")
                        .HasColumnName("id_centro");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("integer")
                        .HasColumnName("id_periodo");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("text")
                        .HasColumnName("nivel_educativo");

                    b.Property<decimal?>("PromedioCalificaciones")
                        .HasColumnType("numeric")
                        .HasColumnName("promedio_calificaciones");

                    b.Property<decimal?>("TasaAprobacion")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_aprobacion");

                    b.Property<decimal?>("TasaRepitencia")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_repitencia");

                    b.Property<decimal?>("TasaSobreedad")
                        .HasColumnType("numeric")
                        .HasColumnName("tasa_sobreedad");

                    b.Property<int?>("TotalEstudiantes")
                        .HasColumnType("integer")
                        .HasColumnName("total_estudiantes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdRendimiento");

                    b.HasIndex("IdCentro");

                    b.HasIndex("IdPeriodo");

                    b.ToTable("rendimiento_academico", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.ServicioBasico", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdServicio"));

                    b.Property<decimal?>("AccesoInternet")
                        .HasColumnType("numeric")
                        .HasColumnName("acceso_internet");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<decimal?>("CoberturaAguaPotable")
                        .HasColumnType("numeric")
                        .HasColumnName("cobertura_agua_potable");

                    b.Property<decimal?>("CoberturaEnergiaElectrica")
                        .HasColumnType("numeric")
                        .HasColumnName("cobertura_energia_electrica");

                    b.Property<decimal?>("CoberturaSaneamientoBasico")
                        .HasColumnType("numeric")
                        .HasColumnName("cobertura_saneamiento_basico");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FuenteDatos")
                        .HasColumnType("text")
                        .HasColumnName("fuente_datos");

                    b.Property<int>("IdMunicipio")
                        .HasColumnType("integer")
                        .HasColumnName("id_municipio");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdServicio");

                    b.HasIndex("IdMunicipio");

                    b.ToTable("servicios_basicos", (string)null);
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.AbandonoCausanteZona", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.CausanteAbandono", "Causante")
                        .WithMany()
                        .HasForeignKey("IdCausante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAD.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Causante");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.CentroEducativo", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.DistritoEducativo", "Distrito")
                        .WithMany("CentrosEducativos")
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAD.Domain.Entities.Municipio", "Municipio")
                        .WithMany("CentrosEducativos")
                        .HasForeignKey("MunicipioIdMunicipio");

                    b.Navigation("Distrito");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.DemocratizacionEducativa", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.DistritoEducativo", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.RegionalEducativa", "Regional")
                        .WithMany("DistritosEducativos")
                        .HasForeignKey("IdRegional")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAD.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioIdMunicipio");

                    b.HasOne("SIPAD.Domain.Entities.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaIdProvincia");

                    b.Navigation("Municipio");

                    b.Navigation("Provincia");

                    b.Navigation("Regional");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.EstadisticaAbandono", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.CentroEducativo", "Centro")
                        .WithMany()
                        .HasForeignKey("IdCentro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAD.Domain.Entities.PeriodoAcademico", "Periodo")
                        .WithMany()
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.FactorRiesgoSocial", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.IndicadorSocioeconomico", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.Municipio", "Municipio")
                        .WithMany("IndicadoresSocioeconomicos")
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.Provincia", "Provincia")
                        .WithMany("Municipios")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.RecursoEducativo", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.CentroEducativo", "Centro")
                        .WithMany()
                        .HasForeignKey("IdCentro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAD.Domain.Entities.PeriodoAcademico", "Periodo")
                        .WithMany()
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.RendimientoAcademico", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.CentroEducativo", "Centro")
                        .WithMany("RendimientosAcademicos")
                        .HasForeignKey("IdCentro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAD.Domain.Entities.PeriodoAcademico", "Periodo")
                        .WithMany("RendimientosAcademicos")
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Centro");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.ServicioBasico", b =>
                {
                    b.HasOne("SIPAD.Domain.Entities.Municipio", "Municipio")
                        .WithMany("ServiciosBasicos")
                        .HasForeignKey("IdMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.CentroEducativo", b =>
                {
                    b.Navigation("RendimientosAcademicos");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.DistritoEducativo", b =>
                {
                    b.Navigation("CentrosEducativos");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("CentrosEducativos");

                    b.Navigation("IndicadoresSocioeconomicos");

                    b.Navigation("ServiciosBasicos");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.PeriodoAcademico", b =>
                {
                    b.Navigation("RendimientosAcademicos");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.Provincia", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("SIPAD.Domain.Entities.RegionalEducativa", b =>
                {
                    b.Navigation("DistritosEducativos");
                });
#pragma warning restore 612, 618
        }
    }
}
